version: "3.9"

services:

  springboot_webapi_gradle_mysql_service:
    image: mysql:5.7
    container_name: springboot_webapi_gradle_mysql_service
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dumb_db
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD
      timeout: 5s
      retries: 10